name: Superchicken
version: '${version}'
main: com.zszf.superchicken.Superchicken
commands:
  item:
    aliases:
      - "delitem"
      - "di"
    description: "删除掉落物"
    usage: "/delitem"
permissions:
  superchicken.use:
    default: true
    description: "permission that owner can use chicken dupe"